AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain

#IAMRole Parameters
  IAMRolePath:
    Type: String
    Description: IAM Role yaml path
#GlueDB Parameters
  GlueDBPath:
    Type: String
    Description: Database yaml path     
#LF Parameters
  lfPath:
    Type: String
    Description: 'LF Stack S3 URL of the nested stack template'    
  DataLakeBucket:
    Type: String
    Description: 'Name of the S3 bucket to use as the data lake'
    Default: "sanbox---trusted"
  CodeBuildRole:
    Type: String
    Description: 'Code Build Role Which is used to build all CF reosurces'
    Default: "codebuild-sandbox-governance-service-role"
  ProducerAccountId:
    Type: String
    Description: 'AWS Account ID of the producer account'  
    Default: "117134819170"
  ConsumerAccountId:
    Type: String
    Description: 'AWS Account ID of the Consumer account'
    Default: '020392763922'    
  lfpermissionsPath:
    Type: String
    Description: 'LF Permissions Stack S3 URL of the nested stack template'
#Glue Job Parameters
  ScriptBucketName:
    Type: String
    Description: 'Name of the S3 bucket for Glue scripts'
    Default: 'mycicd-bucket-ap'
  ScriptKey:
    Type: String
    Description: 'S3 key for the Glue job script'
    Default: 'scripts/gluejob.py'    
  GlueJobPath:
    Type: String
    Description: 'Glue Job yaml path Parameters'     
  SourceBucketName:
    Type: String
    Description: Name of the Source S3 bucket
    Default: 'mycicd-bucket-ap'   
  TargetBucketName:
    Type: String
    Description: Name of the target S3 bucket
    Default: 'mycicd-bucket-ap'
  RetentionInDays:
    Type: Number
    Default: 30
    Description: The number of days to retain log events

#Lambda Parameters
  LambdaPath:
    Type: String
    Description: 'Lambda yaml path Parameters' 
  Runtime:
    Type: String
    Default: python3.9
    AllowedValues:
      - python3.8
      - python3.9
      - python3.10
    Description: Runtime for Lambda function
  S3BucketName:
    Type: String
    Description: S3 bucket containing Lambda code
    Default: 'mycicd-bucket-ap'
  S3Key:
    Type: String
    Default: 'lambda/Function.py'
    Description: S3 key for Lambda code package
  BatchSize:
    Type: Number
    Default: 10
    Description: The maximum number of messages to retrieve per batch
    MinValue: 1
    MaxValue: 10000
  SQSQueue:
    Type: String
    Description: The Name of the SQS Queue to poll
    Default: 'TestQueue'
  SQSQueueArn:
    Type: String
    Description: The Name of the SQS Queue to poll
    Default: 'arn:aws:sqs:us-east-1:903432419063:TestQueue'


Resources:

  IAMRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref IAMRolePath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        DataLakeBucketName: !Ref DataLakeBucket
        SQSQueueArn: !Ref SQSQueueArn

  LakeFormationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMRoles    
    Properties:
      TemplateURL: !Ref lfPath
      Parameters:
        DataLakeBucketName: !Ref DataLakeBucket
        CodeBuildRole: !Ref CodeBuildRole
        LFServiceRoleArn: !GetAtt IAMRoles.Outputs.LFServiceRoleArn
        ProducerAccountId: !Ref ProducerAccountId

  GlueDatabase:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref GlueDBPath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName

  LFPermissions:
    Type: AWS::CloudFormation::Stack
    DependsOn: GlueDatabase
    DependsOn: LakeFormationStack    
    Properties:
      TemplateURL: !Ref lfpermissionsPath
      Parameters:
        DatabaseName: !GetAtt GlueDatabase.Outputs.DatabaseName
        ProducerAccountId: !Ref ProducerAccountId
        ConsumerAccountId: !Ref ConsumerAccountId

  GlueJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref GlueJobPath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        ScriptBucketName: !Ref ScriptBucketName
        ScriptKey: !Ref ScriptKey
        SourceBucketName: !Ref SourceBucketName
        TargetBucketName: !Ref TargetBucketName
        JobRoleArn: !GetAtt IAMRoles.Outputs.GlueJobRoleArn
        RetentionInDays: !Ref RetentionInDays

  Lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LambdaPath
      Parameters:
        EnvType: !Ref EnvType 
        DomainName: !Ref DomainName
        Runtime: !Ref Runtime
        S3BucketName: !Ref S3BucketName
        S3Key: !Ref S3Key
        BatchSize: !Ref BatchSize
        LambdaExecutionRoleArn: !GetAtt IAMRoles.Outputs.LambdaExecutionRoleArn
        SQSQueue: !Ref SQSQueue
        RetentionInDays: !Ref RetentionInDays

Outputs:

  LFServiceRoleArn:
    Description: 'LF Service IAM Role'
    Value: !GetAtt IAMRoles.Outputs.LFServiceRoleArn
    Export:
      Name: LFServiceRoleArn

  GlueJobRoleArn:      
    Description: 'Glue Job IAM Role'
    Value: !GetAtt IAMRoles.Outputs.GlueJobRoleArn

  LambdaExecutionRoleArn:
    Description: 'Name of the Lambda Execution Role'
    Value: !GetAtt IAMRoles.Outputs.LambdaExecutionRoleArn     
          
  DatabaseName:
    Description: 'Name of the Glue Database'
    Value:  !GetAtt GlueDatabase.Outputs.DatabaseName

  JobName:
    Description: 'The name of the created Glue Job'
    Value: !GetAtt GlueJob.Outputs.JobName

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt Lambda.Outputs.LambdaFunctionArn